# .github/workflows/containerization.yml

name: Containerization Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-username/hello-world:${{ github.sha }}
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Deploy to AWS server
        uses: appleboy/ssh-action@master
        with:
          host: your-aws-server-ip
          username: your-aws-server-username
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker stop hello-world || true
            docker rm hello-world || true
            docker pull your-docker-username/hello-world:${{ github.sha }}
            docker run -d -p 80:80 --name hello-world your-docker-username/hello-world:${{ github.sha }}
